# Generated by Django 4.0.6 on 2022-08-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(default=' ', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
